name: exercicio

on:
  push:
  
jobs:

  checkout_code:
    name: faz checkout
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repositorio
      uses: actions/checkout@v3.3.0
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ vars.NAME }}
        path: .
        
     
